### PR TITLE
Doc: Web worker functions and external deps

### LINKED ISSUE #6: Unable to call external modules inside a workerized function
## Issue

I realize that you can’t inline `useWorker(function)` if  `function` uses imported modules and isn’t written in its own file. Basically, having side-effects in your functions. Webpack doesn’t seem to compile the dependencies as-is.

## Error
Example error: js_cookie__WEBPACK_IMPORTED_MODULE_7___default

js-cookie being the npm module.

## Solution
1. Add documentation to warn users that you must move web worker functions into their own files with their own imports.
2. Maybe even explicitly throw Errors

### PR DESCRIPTION
**Pull request by dangdennis**
Fixes #6 

Can consider cutting down on the example length.

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks!
Yeah, it's a big long. Maybe, you want to use `<details>`?

Do you notice that it's not only about the external module, but just a function outside:
```javascript
const fib = i => (i <= 1 ? i : fib(i - 1) + fib(i - 2));

const calcFib = (x) => {
  if (x > 40) throw new Error('input too learge (> 40)');
  return fib(x);
};

const CalcFib = ({ count }) => {
  const { result, error } = useWorker(calcFib, count);
  if (error) return <div>Error:{error}</div>;
  return <div>Result:{result}</div>;
};
```

This doesn't work either.

**Comment by dangdennis** [comment]
I assumed having the first arg in the same file worked because your codesandbox worked. Then again, they indeed were separate files.

Ideally users can just do useWorker everywhere and use Async/await to return their results.

You should look into how Workerize and Comlink works if you haven’t seen it already. 

Wrapping those libraries would be a fun use case.

**Comment by dai-shi** [comment]
I looked at those two libs plus greenlet.
I didn't come up with ideas to nicely wrap comlink, and I wanted to experiment **non-RPC** style.
Yeah, we've got to do something to improve.

> Comlink and workerize both have a webpack loader libraries.

🤔

**Comment by dai-shi** [comment]
Maybe one question would be what's wrong with comlink.
What would a React hook add benefit to it?

**Comment by dangdennis** [comment]
Oops, I accidentally ran Prettier file altogether.

That's a good question to focus on. Looking at the Comlink API now, I don't really like the class based design. Wouldn't greenlet then be the most adaptable and compatible API? 

I wouldn't know how to use workers in a non-RPC method. Is this possible with the current web api?

**Comment by dai-shi** [comment]
> Wouldn't greenlet then be the most adaptable and compatible API?

yes.

> I wouldn't know how to use workers in a non-RPC method.

My idea is to use generators. Please see `example/05_generator`.
This can't be done with greenlet. (once with confident, a PR to greenlet might be an option, but the situation is a bit different. in the hooks world, we don't need generator interface in the UI thread.)

**Comment by dai-shi** [comment]
I'm very sorry. I don't remember why I didn't merge this back then.

**Pull request merged**
